/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sge;

/**
 *
 * @author gabri
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mainMenu = new javax.swing.JMenuBar();
        menuCadastros = new javax.swing.JMenu();
        rf_001 = new javax.swing.JMenuItem();
        rf_002 = new javax.swing.JMenuItem();
        rf_003 = new javax.swing.JMenuItem();
        rf_004 = new javax.swing.JMenuItem();
        rf_005 = new javax.swing.JMenuItem();
        menuFinanceiro = new javax.swing.JMenu();
        menuRelatorios = new javax.swing.JMenu();
        rf_006 = new javax.swing.JMenuItem();
        rf_007 = new javax.swing.JMenuItem();
        rf_008 = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SGE - Sistema de Gestão Escolar");
        setMinimumSize(new java.awt.Dimension(400, 300));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo.png"))); // NOI18N
        jLabel1.setToolTipText("");

        mainMenu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        mainMenu.setMargin(new java.awt.Insets(4, 4, 4, 4));

        menuCadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuCadastrar.png"))); // NOI18N
        menuCadastros.setText("Cadastrar");
        menuCadastros.setActionCommand("Cadastros");
        menuCadastros.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        rf_001.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rf_001.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/aluno.png"))); // NOI18N
        rf_001.setText("Aluno");
        rf_001.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rf_001ActionPerformed(evt);
            }
        });
        menuCadastros.add(rf_001);

        rf_002.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rf_002.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/professor.png"))); // NOI18N
        rf_002.setText("Professor");
        rf_002.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rf_002ActionPerformed(evt);
            }
        });
        menuCadastros.add(rf_002);

        rf_003.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rf_003.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/turma.png"))); // NOI18N
        rf_003.setText("Turma");
        menuCadastros.add(rf_003);

        rf_004.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rf_004.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/curso.png"))); // NOI18N
        rf_004.setText("Curso");
        rf_004.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rf_004ActionPerformed(evt);
            }
        });
        menuCadastros.add(rf_004);

        rf_005.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rf_005.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/funcionario.png"))); // NOI18N
        rf_005.setText("Funcionário");
        menuCadastros.add(rf_005);

        mainMenu.add(menuCadastros);

        menuFinanceiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuFinanceiro.png"))); // NOI18N
        menuFinanceiro.setText("Financeiro");
        mainMenu.add(menuFinanceiro);

        menuRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuRelatorios.png"))); // NOI18N
        menuRelatorios.setText("Relatórios");

        rf_006.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rf_006.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/notas.png"))); // NOI18N
        rf_006.setText("Financeiro");
        menuRelatorios.add(rf_006);

        rf_007.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rf_007.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/notas.png"))); // NOI18N
        rf_007.setText("Notas");
        menuRelatorios.add(rf_007);

        rf_008.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rf_008.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/frequencias.png"))); // NOI18N
        rf_008.setText("Frequências");
        menuRelatorios.add(rf_008);

        mainMenu.add(menuRelatorios);

        menuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuSair.png"))); // NOI18N
        menuSair.setText("Sair");
        menuSair.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        menuSair.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        mainMenu.add(menuSair);

        setJMenuBar(mainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(314, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("SGE - Sistema de Gestão Escolar");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rf_001ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rf_001ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rf_001ActionPerformed

    private void rf_004ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rf_004ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rf_004ActionPerformed

    private void rf_002ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rf_002ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rf_002ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenu menuFinanceiro;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenuItem rf_001;
    private javax.swing.JMenuItem rf_002;
    private javax.swing.JMenuItem rf_003;
    private javax.swing.JMenuItem rf_004;
    private javax.swing.JMenuItem rf_005;
    private javax.swing.JMenuItem rf_006;
    private javax.swing.JMenuItem rf_007;
    private javax.swing.JMenuItem rf_008;
    // End of variables declaration//GEN-END:variables
}
