/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package sge;

import  baseCoding.Aluno;
import javax.swing.JOptionPane;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author gabri
 */
public class rf_001 extends javax.swing.JInternalFrame {

    public rf_001() {
        initComponents();
    }

    private boolean validarNome(String nome) {
        // Verifique se o nome não está vazio
        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nome inválido");
            return false;
        }
    
        // Adicione outras validações específicas para o nome, se necessário
    
        return true;
    }
    
    private boolean validarSobrenome(String sobrenome) {
        // Verifique se o sobrenome não está vazio
        if (sobrenome.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sobrenome inválido");
            return false;
        }
    
        // Adicione outras validações específicas para o sobrenome, se necessário
    
        return true;
    }
    
    private boolean validarDataNascimento(String dataNascimento) {
        // Verifique se a data de nascimento não está vazia
        if (dataNascimento.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Data de nascimento inválida");
            return false;
        }
    
        // Adicione outras validações específicas para a data de nascimento, se necessário
    
        return true;
    }
    
    private boolean validarCPF(String cpf) {
        // Remova caracteres especiais do CPF (pontos e traço)
        cpf = cpf.replaceAll("[^0-9]", "");
    
        // Verifique se o CPF possui 11 dígitos
        if (cpf.length() != 11) {
            JOptionPane.showMessageDialog(this, "CPF inválido");
            return false;
        }
    
        // Verifique se todos os dígitos do CPF são iguais (CPF inválido)
        if (cpf.matches("(\\d)\\1{10}")) {
            JOptionPane.showMessageDialog(this, "CPF inválido");
            return false;
        }
    
        // Calcule o primeiro dígito verificador
        int soma = 0;
        for (int i = 0; i < 9; i++) {
            soma += (cpf.charAt(i) - '0') * (10 - i);
        }
        int digito1 = 11 - (soma % 11);
        if (digito1 > 9) {
            digito1 = 0;
        }
    
        // Calcule o segundo dígito verificador
        soma = 0;
        for (int i = 0; i < 10; i++) {
            soma += (cpf.charAt(i) - '0') * (11 - i);
        }
        int digito2 = 11 - (soma % 11);
        if (digito2 > 9) {
            digito2 = 0;
        }
    
        // Verifique se os dígitos verificadores calculados são iguais aos dígitos informados
        if (digito1 != (cpf.charAt(9) - '0') || digito2 != (cpf.charAt(10) - '0')) {
            JOptionPane.showMessageDialog(this, "CPF inválido");
            return false;
        }
    
        return true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents

    String mysqlDateString;

    private void initComponents() {

        novoAlunoInternalLogo = new javax.swing.JLabel();
        cadastroAluno = new javax.swing.JLabel();
        novoAlunoSobrenomeLabel = new javax.swing.JLabel();
        novoAlunoNome = new javax.swing.JTextField();
        novoAlunoLabel = new javax.swing.JLabel();
        novoAlunoSobrenome = new javax.swing.JTextField();
        novoAlunoCPF = new javax.swing.JTextField();
        novoAlunoDN = new javax.swing.JFormattedTextField();
        novoAlunoDNLabel = new javax.swing.JLabel();
        novoAlunoCPFLabel = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        novoAlunoResp = new javax.swing.JLabel();
        novoAlunoRespField = new javax.swing.JTextField();
        novoAlunoCPFRespLabel = new javax.swing.JLabel();
        novoAlunoCPFResp = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        respAviso = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Cadastro de Alun@");

        novoAlunoInternalLogo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        novoAlunoInternalLogo.setForeground(new java.awt.Color(51, 51, 51));
        novoAlunoInternalLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novoAlunoInternal.png"))); // NOI18N

        cadastroAluno.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cadastroAluno.setForeground(new java.awt.Color(51, 51, 51));
        cadastroAluno.setText("Cadastro de Alun@");

        novoAlunoSobrenomeLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        novoAlunoSobrenomeLabel.setForeground(new java.awt.Color(51, 51, 51));
        novoAlunoSobrenomeLabel.setText("Sobrenome");

        novoAlunoNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        novoAlunoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoAlunoNomeActionPerformed(evt);
            }
        });

        novoAlunoLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        novoAlunoLabel.setForeground(new java.awt.Color(51, 51, 51));
        novoAlunoLabel.setText("Nome");

        novoAlunoSobrenome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        novoAlunoSobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoAlunoSobrenomeActionPerformed(evt);
            }
        });

        novoAlunoCPF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        novoAlunoDN.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        novoAlunoDN.setToolTipText("xx/xx/xxxx");
        novoAlunoDN.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        novoAlunoDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoAlunoDNActionPerformed(evt);
            }
        });

        novoAlunoDNLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        novoAlunoDNLabel.setForeground(new java.awt.Color(51, 51, 51));
        novoAlunoDNLabel.setText("Data de Nascimento");

        novoAlunoCPFLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        novoAlunoCPFLabel.setForeground(new java.awt.Color(51, 51, 51));
        novoAlunoCPFLabel.setText("CPF");

        btnCadastrar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        novoAlunoResp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        novoAlunoResp.setForeground(new java.awt.Color(51, 51, 51));
        novoAlunoResp.setText("Responsável");

        novoAlunoRespField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        novoAlunoRespField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoAlunoRespFieldActionPerformed(evt);
            }
        });

        novoAlunoCPFRespLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        novoAlunoCPFRespLabel.setForeground(new java.awt.Color(51, 51, 51));
        novoAlunoCPFRespLabel.setText("CPF Responsável");

        novoAlunoCPFResp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        respAviso.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        respAviso.setForeground(new java.awt.Color(51, 51, 51));
        respAviso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        respAviso.setText("Somente se necessário um responsável");
        respAviso.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(novoAlunoInternalLogo)
                        .addGap(60, 60, 60)
                        .addComponent(cadastroAluno))
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(novoAlunoDN)
                            .addComponent(novoAlunoLabel)
                            .addComponent(novoAlunoNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(novoAlunoDNLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(novoAlunoCPFLabel)
                            .addComponent(novoAlunoSobrenomeLabel)
                            .addComponent(novoAlunoSobrenome, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(novoAlunoCPF)
                            .addComponent(btnCadastrar, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(novoAlunoRespField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(novoAlunoResp))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(novoAlunoCPFRespLabel)
                            .addComponent(novoAlunoCPFResp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(respAviso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(novoAlunoInternalLogo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(cadastroAluno)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(novoAlunoSobrenomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(novoAlunoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novoAlunoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(novoAlunoSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novoAlunoDNLabel)
                    .addComponent(novoAlunoCPFLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novoAlunoDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(novoAlunoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(respAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(novoAlunoResp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(novoAlunoRespField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(novoAlunoCPFRespLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(novoAlunoCPFResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void novoAlunoDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoAlunoDNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novoAlunoDNActionPerformed

    private void novoAlunoSobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoAlunoSobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novoAlunoSobrenomeActionPerformed

    private void novoAlunoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoAlunoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novoAlunoNomeActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        
        // Dentro do método btnCadastrarActionPerformed()
    try {
        // Obtém a data de nascimento no formato dd/MM/yyyy
        String dataNascimento = novoAlunoDN.getText();

        // Converte a data para o formato do MySQL (yyyy-MM-dd)
        SimpleDateFormat inputFormat = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat outputFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date date = inputFormat.parse(dataNascimento);
        mysqlDateString = outputFormat.format(date);
    } catch (ParseException e) {
        // Trate qualquer exceção que possa ocorrer durante a conversão
        e.printStackTrace();
    }

    // Verifique se mysqlDateString não está vazia antes de usá-la
    if (mysqlDateString != null && !mysqlDateString.isEmpty()) {
        // Faça o que você precisa com mysqlDateString
        System.out.println("Data de nascimento em formato MySQL: " + mysqlDateString);

        if (validarNome(novoAlunoNome.getText()) && validarSobrenome(novoAlunoSobrenome.getText()) &&
            validarDataNascimento(mysqlDateString) && validarCPF(novoAlunoCPF.getText())) {

            Aluno aluno = new Aluno(novoAlunoNome.getText(), novoAlunoSobrenome.getText(), mysqlDateString, novoAlunoCPF.getText(), "Av n sei onde", novoAlunoResp.getText(), novoAlunoCPFResp.getText(), 2021002);
            aluno.cadastrarAluno(aluno);

            JOptionPane.showMessageDialog(this, "Cadastro bem sucedido!");

            // Feche o formulário
            dispose();
            }
        
    } else {
        // Caso mysqlDateString esteja vazia, mostre uma mensagem de erro ou realize outra ação apropriada
        System.out.println("Erro ao converter a data de nascimento.");
    }

        
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void novoAlunoRespFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoAlunoRespFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novoAlunoRespFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JLabel cadastroAluno;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField novoAlunoCPF;
    private javax.swing.JLabel novoAlunoCPFLabel;
    private javax.swing.JTextField novoAlunoCPFResp;
    private javax.swing.JLabel novoAlunoCPFRespLabel;
    private javax.swing.JFormattedTextField novoAlunoDN;
    private javax.swing.JLabel novoAlunoDNLabel;
    private javax.swing.JLabel novoAlunoInternalLogo;
    private javax.swing.JLabel novoAlunoLabel;
    private javax.swing.JTextField novoAlunoNome;
    private javax.swing.JLabel novoAlunoResp;
    private javax.swing.JTextField novoAlunoRespField;
    private javax.swing.JTextField novoAlunoSobrenome;
    private javax.swing.JLabel novoAlunoSobrenomeLabel;
    private javax.swing.JLabel respAviso;
    // End of variables declaration//GEN-END:variables
}
